### ISSUE TITLE
Zero Division Error

### ISSUE THREAD

**Issue by KittyOverlord** [dpitch40/astro2#18]
Stack Trace:
app installed: atomicwrites==1.4.0,attrs==20.3.0,colorama==0.4.4,iniconfig==1.1.1,packaging==20.9,pluggy==0.13.1,py==1.10.0,pygame==2.0.1,pyparsing==2.4.7,pytest==6.2.2,PyYAML==5.4.1,thorpy==1.7,toml==0.10.2
app run-test-pre: PYTHONHASHSEED='618'
app run-test: commands[0] | python testgame.py
pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "testgame.py", line 96, in <module>
    main()
  File "testgame.py", line 81, in main
    group.update()
  File "C:\Users\kitty\astro2\.tox\py38\lib\site-packages\pygame\sprite.py", line 531, in update
    sprite.update(*args, **kwargs)
  File "C:\Users\kitty\astro2\astro\astro_sprite.py", line 120, in update
    self._tick()
  File "C:\Users\kitty\astro2\astro\timekeeper.py", line 15, in _tick
    self.tick(now, elapsed)
  File "C:\Users\kitty\astro2\astro\ship.py", line 43, in tick
    self.update_velocity(elapsed)
  File "C:\Users\kitty\astro2\astro\ship.py", line 100, in update_velocity
    self.accelerate_toward(elapsed, targetx, targety)
  File "C:\Users\kitty\astro2\astro\astro_sprite.py", line 176, in accelerate_toward
    self.speedx += dx * max_accel / dv
ZeroDivisionError: float division by zero
ERROR: InvocationError for command 'C:\Users\kitty\astro2\.tox\py38\Scripts\python.EXE' testgame.py (exited with code 1)
Method To Reproduce: I moved the screen around, like maybe a few inches, and than it crashed and gave me a Zero Division Error. I think that it has to do with the homing projectile.

**Comment by KittyOverlord** [comment]
Actually, its prolly the enemy ships.
